language: php

dist: trusty
sudo: required

php:
  - "7.0"
  - "7.1"

before_script:
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpspec --config=phpspec.yml run

after_script:
  - vendor/bin/codacycoverage clover build/coverage.xml